### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adamski** [Agorise/c-ipfs#10]
This is an extremely promising project which seems very thin on documentation. 

Is there anywhere with a clear list of todo items, whats working/whats not/roadmap etc?

Is it being used in a live project?

**Comment by thigur** [comment]
Hope you've found this by now.
Specs:  https://github.com/ipfs/specs
IPFS Implementation Doc:  https://github.com/ipfs/specs/blob/master/overviews/implement-ipfs.md

**Comment by Agorise** [comment]
> This is an extremely promising project which seems very thin on documentation.
> 
> Is there anywhere with a clear list of todo items, whats working/whats not/roadmap etc?
> 
> Is it being used in a live project?

yes, the PalmPay point of sale app, the Crystal mobile wallet, and the Morphit bridge. PalmPay is live now, but will soon use c-ipfs for backups, comm with our full nodes (no more use of http or dns), and also as the "app store" for our apps so that they no longer rely on google or apple for approval or updates. 
 
as for Docs, sadly, we really have not had time or the budget to produce them.
